#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'Resume', url: 'pages/resume.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

resume: >
  # Resume
  [Test](dog.jpg)
  
  ![Drag Racing](dog.jpg)
contact: >
  # Contact

  Please contact me [through my email](mailto:rmenon1998@gmail.com) or [connect with me on Linkedin](https://www.linkedin.com/in/rahulmenon98/)
#-------------------------------
# Work Section

projects:
- {name: 'Garbage Segregation', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Neighborhood Clustering', folder: 'proj-2', file: 'projects/proj-2.html'}


#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/phenomenon98'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/rahulmenon98/'}
- {icon: 'envelope', link: 'mailto:rmenon1998@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
